title: Elastic SIEM Lab
description: This is a project base on Elastic SIEM. The lab includes a Kali Linux virtual machine configured to generate security events, which are then collected and analyzed by Elastic SIEM.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
